//  SECCIÓN DE DECLARACIÓN DE INFORMACIÓN ESTÁTICA
let DATOSAPP = [{
    "id": 1,
    "ciudad": "Shahre Jadide Andisheh",
    "pais": "Iran",
    "codigo": "IR",
    "calle": "Kensington"
  }, {
    "id": 2,
    "ciudad": "Bagiktinggang",
    "pais": "Indonesia",
    "codigo": "ID",
    "calle": "Birchwood"
  }, {
    "id": 3,
    "ciudad": "Slobodskoy",
    "pais": "Russia",
    "codigo": "RU",
    "calle": "Bonner"
  }, {
    "id": 4,
    "ciudad": "Ngulahan",
    "pais": "Indonesia",
    "codigo": "ID",
    "calle": "7th"
  }, {
    "id": 5,
    "ciudad": "Saint-Quentin-en-Yvelines",
    "pais": "France",
    "codigo": "FR",
    "calle": "7th"
  }, {
    "id": 6,
    "ciudad": "Rio Claro",
    "pais": "Brazil",
    "codigo": "BR",
    "calle": "Dennis"
  }, {
    "id": 7,
    "ciudad": "Ercheng",
    "pais": "China",
    "codigo": "CN",
    "calle": "Bobwhite"
  }, {
    "id": 8,
    "ciudad": "Oliveirinha",
    "pais": "Portugal",
    "codigo": "PT",
    "calle": "Coolidge"
  }, {
    "id": 9,
    "ciudad": "Prislonica",
    "pais": "Serbia",
    "codigo": "RS",
    "calle": "Kedzie"
  }, {
    "id": 10,
    "ciudad": "Trincomalee",
    "pais": "Sri Lanka",
    "codigo": "LK",
    "calle": "Sachtjen"
  }, {
    "id": 11,
    "ciudad": "Mindyak",
    "pais": "Russia",
    "codigo": "RU",
    "calle": "Oriole"
  }, {
    "id": 12,
    "ciudad": "San Rafael",
    "pais": "Philippines",
    "codigo": "PH",
    "calle": "Cardinal"
  }, {
    "id": 13,
    "ciudad": "Singgugu",
    "pais": "Indonesia",
    "codigo": "ID",
    "calle": "Gina"
  }, {
    "id": 14,
    "ciudad": "Sidem",
    "pais": "Indonesia",
    "codigo": "ID",
    "calle": "Golf Course"
  }, {
    "id": 15,
    "ciudad": "Junaynat Raslān",
    "pais": "Syria",
    "codigo": "SY",
    "calle": "Dottie"
  }, {
    "id": 16,
    "ciudad": "Ferrol",
    "pais": "Spain",
    "codigo": "ES",
    "calle": "Commercial"
  }, {
    "id": 17,
    "ciudad": "Phù Mỹ",
    "pais": "Vietnam",
    "codigo": "VN",
    "calle": "Annamark"
  }, {
    "id": 18,
    "ciudad": "Neuilly-sur-Marne",
    "pais": "France",
    "codigo": "FR",
    "calle": "Harper"
  }, {
    "id": 19,
    "ciudad": "Kharabali",
    "pais": "Russia",
    "codigo": "RU",
    "calle": "Eagan"
  }, {
    "id": 20,
    "ciudad": "Campinas",
    "pais": "Brazil",
    "codigo": "BR",
    "calle": "Colorado"
  }, {
    "id": 21,
    "ciudad": "Kole",
    "pais": "Uganda",
    "codigo": "UG",
    "calle": "Lighthouse Bay"
  }, {
    "id": 22,
    "ciudad": "Ocho Rios",
    "pais": "Jamaica",
    "codigo": "JM",
    "calle": "4th"
  }, {
    "id": 23,
    "ciudad": "Boucinha",
    "pais": "Portugal",
    "codigo": "PT",
    "calle": "Mcbride"
  }, {
    "id": 24,
    "ciudad": "Sigeng",
    "pais": "China",
    "codigo": "CN",
    "calle": "Briar Crest"
  }, {
    "id": 25,
    "ciudad": "Bandar-e Lengeh",
    "pais": "Iran",
    "codigo": "IR",
    "calle": "Springview"
  }, {
    "id": 26,
    "ciudad": "Nakusp",
    "pais": "Canada",
    "codigo": "CA",
    "calle": "Lindbergh"
  }, {
    "id": 27,
    "ciudad": "Honglan",
    "pais": "China",
    "codigo": "CN",
    "calle": "Sunfield"
  }, {
    "id": 28,
    "ciudad": "Targowisko",
    "pais": "Poland",
    "codigo": "PL",
    "calle": "Onsgard"
  }, {
    "id": 29,
    "ciudad": "San Miguel",
    "pais": "Paraguay",
    "codigo": "PY",
    "calle": "Crowley"
  }, {
    "id": 30,
    "ciudad": "Roanoke",
    "pais": "United States",
    "codigo": "US",
    "calle": "Old Gate"
  }, {
    "id": 31,
    "ciudad": "Lokea",
    "pais": "Indonesia",
    "codigo": "ID",
    "calle": "Mallory"
  }, {
    "id": 32,
    "ciudad": "Funaishikawa",
    "pais": "Japan",
    "codigo": "JP",
    "calle": "Forest"
  }, {
    "id": 33,
    "ciudad": "Mouquim",
    "pais": "Portugal",
    "codigo": "PT",
    "calle": "Meadow Valley"
  }, {
    "id": 34,
    "ciudad": "Accha",
    "pais": "Peru",
    "codigo": "PE",
    "calle": "Sycamore"
  }, {
    "id": 35,
    "ciudad": "Aramayuan",
    "pais": "Philippines",
    "codigo": "PH",
    "calle": "Basil"
  }, {
    "id": 36,
    "ciudad": "Ivot",
    "pais": "Russia",
    "codigo": "RU",
    "calle": "Morrow"
  }, {
    "id": 37,
    "ciudad": "Quilpué",
    "pais": "Chile",
    "codigo": "CL",
    "calle": "Marcy"
  }, {
    "id": 38,
    "ciudad": "Mporokoso",
    "pais": "Zambia",
    "codigo": "ZM",
    "calle": "Pawling"
  }, {
    "id": 39,
    "ciudad": "Mīzan Teferī",
    "pais": "Ethiopia",
    "codigo": "ET",
    "calle": "Mallory"
  }, {
    "id": 40,
    "ciudad": "Repatriación",
    "pais": "Paraguay",
    "codigo": "PY",
    "calle": "Florence"
  }, {
    "id": 41,
    "ciudad": "Neftobod",
    "pais": "Tajikistan",
    "codigo": "TJ",
    "calle": "Blaine"
  }, {
    "id": 42,
    "ciudad": "Dananyu",
    "pais": "China",
    "codigo": "CN",
    "calle": "Alpine"
  }, {
    "id": 43,
    "ciudad": "Muncar",
    "pais": "Indonesia",
    "codigo": "ID",
    "calle": "Grim"
  }, {
    "id": 44,
    "ciudad": "Kramsk",
    "pais": "Poland",
    "codigo": "PL",
    "calle": "Washington"
  }, {
    "id": 45,
    "ciudad": "Grecheskoye",
    "pais": "Russia",
    "codigo": "RU",
    "calle": "Northview"
  }, {
    "id": 46,
    "ciudad": "San-Pédro",
    "pais": "Ivory Coast",
    "codigo": "CI",
    "calle": "Mayfield"
  }, {
    "id": 47,
    "ciudad": "Korotych",
    "pais": "Ukraine",
    "codigo": "UA",
    "calle": "Shasta"
  }, {
    "id": 48,
    "ciudad": "Ingå",
    "pais": "Finland",
    "codigo": "FI",
    "calle": "Lighthouse Bay"
  }, {
    "id": 49,
    "ciudad": "Shufeng",
    "pais": "China",
    "codigo": "CN",
    "calle": "Rowland"
  }, {
    "id": 50,
    "ciudad": "Osek nad Bečvou",
    "pais": "Czech Republic",
    "codigo": "CZ",
    "calle": "Manitowish"
  }];